language: android
jdk: oraclejdk7
branches:
  only:
    - develop
    - master
env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a
  global:
  - REPO_SLUG="2359media/voiceover"
  - PRODUCT_NAME="VoicePing"
  - PROJECT_NAME="VoicePing"
  - APP_MANAGER_API_TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTYsImFwaV9rZXkiOiIyMTQ0MTI5Ni0zNTQyLTQ2NmYtYWQ1Yy00OWVmYmRmNjgxZDQifQ.RPGzB2TQbheRVXqOJha_48kERq1NwDHhoOIoSmnYf_g"

android:
  components:
    - build-tools-21.1.1
    - android-21

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest

after_success:
   - chmod a+x ./CI/upload.sh
   - "./CI/upload.sh"